### ISSUE TITLE
[Feature Request] 建议增加代码块折叠功能

### ISSUE THREAD

**Issue by hsxfjames** [0xffff-one/0xffff-flarum#11]
考虑如果代码太长，帖子也相应变长，不太好翻。希望可以加个代码块折叠功能，建议可选如下：

1. 默认折叠
    但是这样如果只是分享较短的内容，体验可能不太好
2. 扩展 Markdown 语法
    可能会有较大工作量
3. 发帖框增加一个是否默认折叠的选项
    不能灵活控制到每一个代码块
4. 其他（逃

**Comment by zgq354** [comment]
比较倾向第二个选项，估计工作量在撸对应的 Parser 的正则表达式上

或许可以根据渲染后的元素高度来决定是否增加折叠？

**Comment by hsxfjames** [comment]
> 根据渲染后的元素高度来决定是否增加折叠

这个高度的选取可能也是众口难调，并且考虑部分浏览器和插件提供锁定字体或字号的功能，简单计算的高度不一定对，可能需要先渲染出一行获得行高，再决定超过多少行折叠~
