### ISSUE TITLE
性能优化：Service Worker 预加载页面

### ISSUE THREAD

**Issue by zgq354** [0xffff-one/0xffff-flarum#12]
把首页缓存到 Service Worker 以后，可以实现秒开的效果，减小白屏时间，类似 YouTube 的首页。

但有个问题，首页是 PHP 渲染生成的，包含了用户的 Session 等信息，不能简单地抽出来。

需要将 PHP 原始硬编码到 HTML 的部分抽离出来，做一个轻量的 App Shell 预置到缓存中。

参考本帖：
https://0xffff.one/d/331/25

**Comment by hsxfjames** [comment]
其实可以先缓存 css/js 等资源，忽略 html 的吧。。逐渐更新过来

**Comment by zgq354** [comment]
已针对 html 做了缓存，css/js 也搞了
