### ISSUE TITLE
[BUG]某些图片上传时报500错误

### ISSUE THREAD

**Issue by ToverPomelo** [0xffff-one/0xffff-flarum#14]
测试用例：https://drive.google.com/file/d/10Lz4XA1JBE9ceA3ioKiDRqjEfsYWnoOn/view?usp=sharing
结果：
![500](https://user-images.githubusercontent.com/20137048/80170634-f8395500-861a-11ea-99a3-3d1b798ae4d8.png)

另排除图片文件大小原因，但不确定跟尺寸有没关系

**Comment by zgq354** [comment]
清除缓存可以了，不清楚什么情况，先关了，再遇到的时候看下
