### ISSUE TITLE
升级 flarum/core 到 v1.0

### ISSUE THREAD

**Issue by zgq354** [0xffff-one/0xffff-flarum#15]
目前站点用的 flarum 还是 beta.13 版，flarum 官方发布了 [beta.14 版本](https://discuss.flarum.org/d/25181-flarum-010-beta14-released)，为了跟上主线的更新，需要升级核心。

由于 beta.14 前后端框架都做了大量的重构和版本升级，所有的魔改与第三方插件都需更新以便兼容
（具体涉及的修改点待梳理）

**Comment by zgq354** [comment]
该升级 beta.15 了，有兴趣的同学可以研究下

**Comment by zgq354** [comment]
该升级到 beta.16 了，哎

**Comment by zgq354** [comment]
由于 beta.13 与 beta.16 相差太远，涉及到了所有的第三方扩展，魔改代码不好一次更新
可以先另外起一套跟上上游的版本单独部署，待稳定后再将主站迁移过去

大致分四步：
1. 0xffff-one/0xffff-flarum 切出新分支，跟上上游版本，单独部署测试环境
2. 在测试环境补完缺失的插件、代码优化与魔改
3. 明确数据迁移方案
4. 将旧站点的代码与数据都迁移至最新版主站

**Comment by zgq354** [comment]
目前在分支 [beta.16](https://github.com/0xffff-one/0xffff-flarum/tree/beta.16) 合并了官方最新的 beta.16 版本，接下来将基于这个版本逐步魔改新功能。

另外我部署了一个部署了项目当前最新代码的测试站点，目前还是官网安装的 beta.16，有任何的功能更新均可在此预览，欢迎各位体验和提出建议：
https://dev.0xffff.one/

待功能稳定、完善了迁移方案以后，我们再将此分支代码合入 master 分支。

相关讨论可以加入站点Q群 or Discord 群组的 #dev 频道。

**Comment by zgq354** [comment]
接下来是安装现有功能所需要的扩展：
（扩展列表待更新）

**Comment by zgq354** [comment]
目前我的思路是，先用社区扩展，如果有不满足功能的地方，再考虑自己 fork 仓库去开发维护。
有个问题是 fork 仓库会有很多跟上主线版本的维护成本，时间精力方面都不太可行（如现在线上版本的搁置状态），所以尽可能地靠近社区多一些。
也欢迎提出你的想法！

**Comment by DICTATOR666** [comment]
站主，社区私信功能可有考虑过，因为有些事情确实只想两个人探讨而不想影响他人，或者其他网站一样个人信息附带邮箱？

**Comment by zgq354** [comment]
> 站主，社区私信功能可有考虑过，因为有些事情确实只想两个人探讨而不想影响他人，或者其他网站一样个人信息附带邮箱？

可以支持不公开讨论的模式

**Comment by zgq354** [comment]
目前装上的扩展：
 - [x] Progressive Web App
 - [x] Fof Webhooks
 - [x] sitemap 插件，输出 sitemap.xml
 - [x] FoF Links，导航栏链接
 - [x] FoF Night Mode 夜间模式
	 - 夜间模式遇到白色图片会亮瞎，可优化
 - [x] FoF SocialProfile 社交链接插件
 - [x] FoF Upload 上传组件
 - [x] FoF User Bio 用户签名
 - [x] Flarum SEO 优化

还有问题的扩展
 - [ ] 中文搜索插件（暂未尝试
 - [ ] Syndication（有兼容问题
 - [ ] MathRen 数学公式（有兼容问题
 - [ ] GitHub Login（有兼容问题

**Comment by zgq354** [comment]
中文站内搜索目前有两种方案：
1. MySQL 全文索引方式实现（参见：https://discuss.flarum.org.cn/d/1216），这种模式，且对数据库有额外开销
2. xunsearch 的方案（目前线上的方案，但插件暂不支持 beta.16 版本，需重新适配，参见：https://discuss.flarum.org.cn/d/1112 ）

所以可以先想办法把 xunsearch 插件移植到 beta.16 上

**Comment by zgq354** [comment]
可以改名了，Flarum 原来发布了 v1.0.0，放心搞起吧

**Comment by zgq354** [comment]
分支：https://github.com/0xffff-one/0xffff-flarum/tree/v1.0

**Comment by zgq354** [comment]
中文搜索问题：先暂时使用 FULLTEXT 索引方案，后续考虑es等搜索插件

**Comment by zgq354** [comment]
已切换至 v1.0
