### ISSUE TITLE
在不同浏览器下 帖子“置顶”效果 失效的发现

### ISSUE THREAD

**Issue by innuaa** [0xffff-one/0xffff-flarum#16]
**Google Chrome**：版本 90.0.4430.72（正式版本） （64 位）
![image](https://user-images.githubusercontent.com/64938861/114879386-ba3cce80-9e33-11eb-8096-8435649eacd5.png)
**Microsoft Edge**：版本 89.0.774.77 (官方内部版本) （64 位）
![image](https://user-images.githubusercontent.com/64938861/114879996-40591500-9e34-11eb-93de-3489ca539ded.png)

**Comment by bobby285271** [comment]
没有认真研究过 Flarum，一些猜测：

图一是在未登录状态下截的，图二是在登录状态下截的，会不会是登录后看过的顶置帖子就自动解除顶置呢？

https://github.com/0xffff-one/sticky/blob/db810392d3cec361492d97eedf363cb6dd9a83ab/src/Listener/PinStickiedDiscussionsToTop.php#L62-L78

**Comment by innuaa** [comment]
> 没有认真研究过 Flarum，一些猜测：
> 
> 图一是在未登录状态下截的，图二是在登录状态下截的，会不会是登录后看过的顶置帖子就自动解除顶置呢？
> 
> https://github.com/0xffff-one/sticky/blob/bec255395c042d8f77b26ffbe8991afa0a5f7369/src/Listener/PinStickiedDiscussionsToTop.php#L62-L91

对滴，但是这样感觉不太符合置顶的一个逻辑？

**Comment by bobby285271** [comment]
> > 没有认真研究过 Flarum，一些猜测：
> > 图一是在未登录状态下截的，图二是在登录状态下截的，会不会是登录后看过的顶置帖子就自动解除顶置呢？
> > https://github.com/0xffff-one/sticky/blob/bec255395c042d8f77b26ffbe8991afa0a5f7369/src/Listener/PinStickiedDiscussionsToTop.php#L62-L91
> 
> 对滴，但是这样感觉不太符合置顶的一个逻辑？

呀这似乎就是设计的问题了，真不太清楚... 估计顶置帖就是为了给新来的用户看的？呆久了之后可能大概会关心新帖吧，顶置帖滞留在顶部可能确实占用了首屏的空间，毕竟一些重要链接也放在顶部导航栏了...

**Comment by zgq354** [comment]
确实是 flarum sticky 本身的设计思路

**Comment by zgq354** [comment]
我先关一下 issue 吧！我们目标先升级基础架构，然后再讨论体验的问题哈哈
