### ISSUE TITLE
【扩展】中文搜索插件针对 v1.0 定制

### ISSUE THREAD

**Issue by zgq354** [0xffff-one/0xffff-flarum#20]
中文站内搜索目前有两种方案：
1. MySQL 全文索引方式实现（参见：https://discuss.flarum.org.cn/d/1216），这种模式，且对数据库有额外开销
2. xunsearch 的方案（目前线上的方案，但插件暂不支持 beta.16 版本，需重新适配，参见：https://discuss.flarum.org.cn/d/1112 ）

所以可以先想办法把 xunsearch 插件移植到 beta.16 上

_Originally posted by @zgq354 in https://github.com/0xffff-one/0xffff-flarum/issues/15#issuecomment-841786522_

**Comment by zgq354** [comment]
相关 issue
https://github.com/jjandxa/flarum-ext-chinese-search/issues/26

**Comment by stimw** [comment]
typesense引擎: [mkm0094/flarum-typesense-chinese-search](https://github.com/mkm0094/flarum-typesense-chinese-search)

**Comment by stimw** [comment]
Another: [ganuonglachanh/flarum-sonic](https://github.com/ganuonglachanh/flarum-sonic)

**Comment by zgq354** [comment]
> Another: [ganuonglachanh/flarum-sonic](https://github.com/ganuonglachanh/flarum-sonic)

在 dev.0xffff.one 测试了一下，搜索功能正常，但搜索帖内关键字时候选状态没有正文的预览（待定位具体原因
![image](https://user-images.githubusercontent.com/9024954/131760116-5e95eb9c-b9bf-43f5-a5f7-57f64a35ad7c.png)

预期情况：
![image](https://user-images.githubusercontent.com/9024954/131760206-a4ca3d8f-785b-48cd-b769-9cd7bfa78590.png)

**Comment by zgq354** [comment]
> > Another: [ganuonglachanh/flarum-sonic](https://github.com/ganuonglachanh/flarum-sonic)
> 
> 在 https://dev.0xffff.one 测试了一下，搜索功能正常，但搜索帖内关键字时候选状态没有正文的预览（待定位具体原因
> ![image](https://user-images.githubusercontent.com/9024954/131760116-5e95eb9c-b9bf-43f5-a5f7-57f64a35ad7c.png)
> 
> 预期情况：
> ![image](https://user-images.githubusercontent.com/9024954/131760206-a4ca3d8f-785b-48cd-b769-9cd7bfa78590.png)

主要是 TitleGamblit 部分的差异：
https://github.com/ganuonglachanh/flarum-sonic/blob/8421240274d4c20eab9afdbb7bd19c9ee3a001d8/src/Gambit/TitleGambit.php#L26

插件替换了 Core 的 FulltextGambit 的实现，但未实现 mostRelevantPost 的功能：
https://github.com/flarum/core/blob/1f2411e15e46fbfb7a499a69a869663c349cca91/src/Discussion/Search/Gambit/FulltextGambit.php#L51

然后返回的数据缺少这个导致：
![image](https://user-images.githubusercontent.com/9024954/131762082-bba7190c-b95f-4bbd-8e3f-2d484dd499f1.png)

**Comment by zgq354** [comment]
> Another: [ganuonglachanh/flarum-sonic](https://github.com/ganuonglachanh/flarum-sonic)

已启用 sonic
https://github.com/0xffff-one/0xffff-env/commit/fea29ec144dc8f137534814c9e1fa29491252dcc
