### ISSUE TITLE
移动端图片点开放大优化

### ISSUE THREAD

**Issue by zgq354** [0xffff-one/0xffff-flarum#24]

**Comment by SkyShi-wvb** [comment]
按理来说是有fancybox插件的，只是没安装

**Comment by zgq354** [comment]
发现了这个
[Fancybox wrapper - Flarum Community](https://discuss.flarum.org/d/26103-fancybox-wrapper)

**Comment by zgq354** [comment]
安排上了：https://github.com/0xffff-one/0xffff-flarum/commit/4dcb8dc4fb7f3ad3e8482ed461525d7f08c4a8d1
