### ISSUE TITLE
jsdelivr.net 的 emoji 表情图片替换

### ISSUE THREAD

**Issue by zgq354** [0xffff-one/0xffff-flarum#40]
众所周知原因 cdn.jsdelivr.net 被干，导致大陆 emoji 图裂掉，需要替换成合适的 cdn（推荐字节的）

**Comment by zgq354** [comment]
### 一种解决方案

把 [`/vendor/flarum/emoji/js/dist/forum.js`](https://github.com/flarum/emoji/blob/c4b741b497cd6691754481fcb0853a6e5069b84f/js/dist/forum.js) 中的
```js
const y="https://cdn.jsdelivr.net/gh/twitter/twemoji@"+/([0-9]+).[0-9]+.[0-9]+/g.exec(h.base)[1]+"/assets/";
```

替换为：
```js
const y="https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/twemoji/"+/([0-9]+).[0-9]+.[0-9]+/g.exec(h.base)[0]+"/";
```

但由于这个插件不是本项目控制范围，目前是在安装依赖之后自动化的方式去编辑，需要修改 composer.json，运行一段 post-install 的 shell 命令。

这种方案还需要一段 `sed` 的命令（参考 [这里的 composer.json 配置](https://github.com/0xffff-one/0xffff-flarum/blob/c2803a2a6f35cb85736bf8a15756a075135adecc/composer.json#L97)），预期得花时间处理一堆转义字符的细节问题，我暂时没时间，欢迎贡献（可以直接留言到 issue）😄

**Comment by qazxcdswe123** [comment]
Consider using [sd](https://github.com/chmln/sd), which support **String-literal mode**
eg:

`sd -s 'const y="https://cdn.jsdelivr.net/gh/twitter/twemoji@"+/([0-9]+).[0-9]+.[0-9]+/g.exec(h.base)[1]+"/assets/";' 'const y="https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/twemoji/"+/([0-9]+).[0-9]+.[0-9]+/g.exec(h.base)[0]+"/";' toReplace.js`

or I prefer

`sd -s 'cdn.jsdelivr.net/gh/twitter/twemoji@' 'lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/twemoji' toReplace.js; sd '/assest/' '/' toReplace.js`

Which will both get the job done perfectly, without escaping a single character.

**Comment by zgq354** [comment]
> Consider using [sd](https://github.com/chmln/sd), which support **String-literal mode** eg:
> 
> `sd -s 'const y="https://cdn.jsdelivr.net/gh/twitter/twemoji@"+/([0-9]+).[0-9]+.[0-9]+/g.exec(h.base)[1]+"/assets/";' 'const y="https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/twemoji/"+/([0-9]+).[0-9]+.[0-9]+/g.exec(h.base)[0]+"/";' toReplace.js`
> 
> or
> 
> `sd -s 'cdn.jsdelivr.net/gh/twitter/twemoji@' 'lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/twemoji' toReplace.js; sd '/assest/' '/' toReplace.js`
> 
> Which will both get the job done perfectly, without escaping a single character.

Great tool, but it is not preinstalled on various Linux distributions, and we just need a pieces of one-time code, additional install this may comes with some cognitive load at Local Development Env (at production env it works well just add one line `apk add sd`).

So I prefered a "sed escaped string generator" rather than introducing a new tool. I just tried [this one](https://dwaves.de/tools/escape/) and it works fine. 😊

**Comment by zgq354** [comment]
fixed.

一点细节：cdn.bytedance.com 目前 twemoji 最高只支持 13，而最新版插件依赖 14 以上版本，所以先写死用 13 的地址，接下来再考虑优化问题
